### ISSUE TITLE
language change is bugged

### ISSUE THREAD

**Issue by locness3** [natixco/tabby#12]
after launching the app (npm start) for the first time, I've had to do three attempts to be able to change to french, setting to spanish than french on last try. and when it works, it's a bit slow
Other than that, thanks for the great app, it looks awesome!

**Comment by natixco** [comment]
I like these types of bugs, because it works for me :D When you load a language for the first time it's slow, because it has to load in the language file, but from that point it'll load faster.

**Comment by locness3** [comment]
Yeah, though isn't there any way to improve the speed?

**Comment by natixco** [comment]
No, I use ngx-translate for that and I don't think that it has any issues since you don't change languages every hour or so.

**Comment by locness3** [comment]
Okay
