### ISSUE TITLE
reload, zoom, and open dev tools are blanked out and not accessible via keyboard either

### ISSUE THREAD

**Issue by locness3** [natixco/tabby#13]
![Capture d’écran 2020-02-24 à 15 57 08](https://user-images.githubusercontent.com/37651007/75162788-5e3e5480-571e-11ea-8935-865768d0372d.png)
from master, macOS 10.11
launching from source with `npm start`
This happens after interacting with any dropdown menu.

**Comment by natixco** [comment]
That's weird. It could be that I disabled the application menu and it will disable those buttons as well. Can you test it if you comment out [this line](https://github.com/natixco/tabby/blob/master/main.ts#L22) will the buttons work?

**Comment by locness3** [comment]
yes that works :)

**Comment by locness3** [comment]
that's weird tho, since the app menu is still working and this only happens with dropdowns. But yeah commenting the line works

**Comment by natixco** [comment]
Cool. I rewrite it then, gonna upload it in a few sec.

**Comment by natixco** [comment]
Uploaded. Could you check it again just to make sure it works?

**Comment by locness3** [comment]
Seems to work fine :)
