### ISSUE TITLE
Doesn't exit properly on mac

### ISSUE THREAD

**Issue by locness3** [natixco/tabby#24]
Built the app for mac from master using `electron-builder -m`.
When I close the window or do Cmd+Q or go to tabby>Quit tabby, the app doesn't exit properly. It stays opened with no window and doesn't respond to any quit command. I am obligated to kill it with Command-Option-Escape, which is kind of annoying

**Comment by natixco** [comment]
You have to close the app from the tray icon. Personally I don't know how it's working on mac, because I don't have one.

**Comment by locness3** [comment]
On macOS the tray icon is... not an icon
![Screen Shot 2020-04-06 at 16 25 25](https://user-images.githubusercontent.com/37651007/78569058-4d0b5c00-7823-11ea-8613-bbd0f98ab20c.png)
When that's fixed you should hide the app from the dock `app.dock.hide()` OR make the app respond to quit commands
