### ISSUE TITLE
App bug in Windows tray.

### ISSUE THREAD

**Issue by LWJerri** [natixco/tabby#38]
Hello! When I open new application, the app creates an icon in the tray, and when I close the app nothing happened and icon stays in-tray.

![image](https://user-images.githubusercontent.com/50290430/90933613-81fe0100-e408-11ea-975d-ec84c5ccf918.png)
![image](https://user-images.githubusercontent.com/50290430/90933799-d7d2a900-e408-11ea-9a40-8425a25962c7.png)

**Comment by natixco** [comment]
I don't think it's necessary, so I've removed the tray icon & menu completely.
