### ISSUE TITLE
Lines for tasks.

### ISSUE THREAD

**Issue by LWJerri** [natixco/tabby#39]
I write pretty structure for my task:
![image](https://user-images.githubusercontent.com/50290430/90934893-c9858c80-e40a-11ea-9acb-b8e093bf5f18.png)

But when looking at the task I see this:
![image](https://user-images.githubusercontent.com/50290430/90934941-dd30f300-e40a-11ea-8d17-c749606ccc0e.png)

Can you add multiple lines for tasks?

**Comment by natixco** [comment]
I've added markdown support for them.
