### ISSUE TITLE
Cannot fill any textbox after alert shown

### ISSUE THREAD

**Issue by edinofricaniago** [natixco/tabby#6]
I try to use your application on my window pc, when i save a new task, your application show an alert and after that i try to make new a task, but cannot fill any textbox in your electron application.

reference for this issue :

https://github.com/natixco/tabby/blob/6becb373ca184cadba973d1fe4a90a4ad78a24ad/src/app/components/pages/new-task/new-task.component.ts#L34

https://stackoverflow.com/questions/56805920/cant-edit-input-text-field-after-window-alert

Thank you, sorry for my bad english.

**Comment by natixco** [comment]
Hey, thank you for reporting this issue! I removed that line and uploaded a new version, so it should work now.

**Comment by locness3** [comment]
If you confirmed ti works, you can close the issue @natixco

**Comment by natixco** [comment]
I know, just wanted to wait for a response :)

**Comment by locness3** [comment]
okay
