### ISSUE TITLE
Unable to download macOS app

### ISSUE THREAD

**Issue by AvidCoder08** [natixco/tabby#61]
How do I download the app for mac, I can't find any packages

**Comment by natixco** [comment]
Only the first version was built for Mac too, but you can download the source and build it by running the command `npm run electron:mac`

**Comment by AvidCoder08** [comment]
it does not work. i just get an error. can someone please make a tutorial

**Comment by AvidCoder08** [comment]
@natixco can you pls elaborate on how to run
